# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e36dd2c0d3425afedf0e380fa336ef87f094889a88659d83197bc66b675d9c52fafad603bdf9b876e7ffb11c40837a0acd97a21907039cfe5d52aed556e753a4

test:
  secret_key_base: 609cf3dfc6bf9150b57dc318a5699fce7fd94c9b410f362ea3dd2b4492489f4da1d0a6985ade5004c33cc23c2b1aa22724b9db3f240fcc431b9c74ed418425b7

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
